name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up dependencies
      run: sudo apt-get install golang gcc libgl1-mesa-dev xorg-dev

    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./guiapp/o2

    - name: Test
      run: go test -v ./guiapp/o2
