name: Release

on:
  push:
    tags:
    - v*

jobs:
  release:
    #runs-on: ubuntu-latest
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - run: cd webui/web && npm install
    - run: cd webui/web && npm run build

    - run: go get github.com/go-bindata/go-bindata/v3/go-bindata@v3.1.3
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@master
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
